### ISSUE TITLE
The autotuner you made for my sampling work has "tuning jitter"

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#55]
Orange Tree Samples needs you to improve your phaselocking autotuner for phaselocking a synthesized (constant/regular) waveform. Currently there's a jitter to the tuning data (going up and down every other data point) resulting in artifacts. I tried all sorts of things, filtering the waveform, highpassing it, trying to get the autotuner to respond better, nothing works. So then I tried a sinewave... still tuning jitter! It seems to happen at a certain frequency, and everything above that frequency fails to be phaselocked. So then OTS re-recorded the samples at a higher sample rate, but that didn't help.

I think I could get some funding for this.

**Comment by RobinSchmidt** [comment]
at which frequency does this happen? so, you say, it happens also with a pure sinewave, if the frequency is above some threshold? is the jitter like a regular (rectangle-ish) up/down or more like noise?

**Comment by elanhickler** [comment]
not noise, up and down, creating tonal artifacts.

I'll have to get you example audio.

**Comment by elanhickler** [comment]
do you know what tuning algorithm i am talking about? do you have it in JURA? Whatever I am using for sampling work should come from JURA so you can improve it from your JURA repository rather than looking at my sampling tools repository.

**Comment by RobinSchmidt** [comment]
i think you are talking about the one in RSLib right? the offline processor. yeah, i would have to drag over the classes in question into the rosic library.

if it happens with a simple sine wave, i probably not need an example audio file. just tell me the parameters (frequency, samplerate, etc) and i could just create a sinewave in my testbed. i'v never seen that happen though. maybe i just didn't test with high enough frequencies

**Comment by elanhickler** [comment]
uhhhhhhhhhhhhhhhhh all of a sudden this morning it seems not to be having an issue... will get back to you on this.

**Comment by RobinSchmidt** [comment]
weird. maybe it happens only in some very specific circumstances? ok, well, that sounds like good news anyway

**Comment by elanhickler** [comment]
[Sustain`n=A1`dyn=loud`register=3.zip](https://github.com/RobinSchmidt/RS-MET/files/1174438/Sustain.n.A1.dyn.loud.register.3.zip)

ok definitely not working. I'm not getting jitter, but the phases are drifting... or it's not even detecting a pitch?

Check out A3. That is failing to get a pitch.

**Comment by RobinSchmidt** [comment]
uhh...i'm just looking at the pitch-detector output data. the signal seems to be actually at A4 (440Hz). but my pitch detector gets a (wiggly) 880Hz, right? and it doesn't handle the start/end transients/pops well.

**Comment by RobinSchmidt** [comment]
so, it looks like the pitch detector has an octave error with this signal. and when you autotune, you get drifting phases? this is an artifact, i would expect when the detected pitch is consistently a little bit above or below the actual pitch. hmm...

**Comment by elanhickler** [comment]
we may need a tuner design for when the pitch is known and stable so you can do some tricks like filtering out everything that is not useful to the tuner, a filter at its fundamental, stuff like that.

**Comment by RobinSchmidt** [comment]
actually, i'm already doing that. i get a preliminary pitch estimate for the whole signal (by autocorrelation of some segment in the middle) and then i bandpass the whole signal at that estimate. only then the zero-crossing detector comes in. it operates on the bandpassed signal

**Comment by RobinSchmidt** [comment]
i think, if you get phase-drift, the issue might be something else. i derive the new readout position from interpolation and integration (i.e. summing up) the pitch-estimates. that process may not be guaranteed to be free of any drift. for example, if my interpolation introduces some bias into the per-sample pitch-estimate, the phase might drift. maybe i should do the interpolation not on the pitch-data but directly on the phase data. or something. like for every zero-crossing (with index n), set the phase to 2*PI*n, interpolate that up to sample-rate and use as readout position. but i'm not sure, if that's the issue

**Comment by RobinSchmidt** [comment]
indeed, any kind of bias in the fundamental frequency would cause a phase drift. the raw zero-crossing data cannot possibly be biased, but after converting to frequency and interpolation to sample-rate, i'm not sure anymore.

**Comment by elanhickler** [comment]
what about autocorrelation? Taking each cycle, then matching it up to the previous one to see where a point needs to occur in time to create a fixed pattern. I thought you were doing something like that already.

**Comment by RobinSchmidt** [comment]
hmmm..."taking each cycle" already implies that we know where one cycle ends and the next starts, but that's what we are trying to figure out. you mean, to use the zero-crossings as initial estimates for cycle starts/ends end then use autocorrelation to refine these estimates?

**Comment by elanhickler** [comment]
hmm.. I think an unfiltered signal (assuming there's no unwanted low frequency stuff messing with the waveform) should technically be used to get perfect results, but if you force the zero crossings to be equidistant, that should provide almost the same results.

**Comment by RobinSchmidt** [comment]
by the way, i was not looking into helmholtz-like autocorrelation methods here precisely because of the possible bias issue. if you run an autocorrelation based pitch detector (with its blocksize arbitraryness) and interpolate that data up to sample-rate, it will not be guaranteed to be bias free. with zero crossings, if you measure one cycle too short, you measure the next one too long (well in a simplified view), totally ruling out any kind of random bias in the estimate

**Comment by RobinSchmidt** [comment]
> I think an unfiltered signal should technically be used to get perfect results, but if you force the zero crossings to be equidistant, that should provide almost the same results.

i'm currently forcing the zero-crossings of the filtered signal to be equidistant. ...but that shouldn't make a big difference either, i think

**Comment by RobinSchmidt** [comment]
> i'm currently forcing the zero-crossings of the filtered signal to be equidistant.

well, technically, i'm not. i'm forcing the pitch to be constant. if i would *literally* enforce equidistant zero crossing, i'd be interpolating the phase data, as i described above. maybe that would be better

**Comment by elanhickler** [comment]
hmm... well, work on it, send me a bill.

**Comment by RobinSchmidt** [comment]
ok, as said, when i'm back from my trip to wacken

**Comment by elanhickler** [comment]
How close are you to being done with the modulation system? I have a deadline to get some samples phaselocked in 7 days, and I have a budget for you of $200, I could increase that budget if you are finding that it's going to take more time.

Here are the samples.

[Sylophone_samples_to_phaselock.zip](https://github.com/RobinSchmidt/RS-MET/files/1229817/Sylophone_samples_to_phaselock.zip)

Each group of files (each note of files) needs to be able to be played together, yet remain completely unflanging (it may be ok if you can't get the attack perfect, but try). This means that the high frequency content (the spiky parts of the waveform) need to really be perfectly stable.

**Comment by elanhickler** [comment]
I think one strategy to get these phaselocked is to subdivide the waveform

**Comment by RobinSchmidt** [comment]
i think, the core design of the mod system is more or less done (for the monophonic case, for poly, i need to add yet more stuff). now i must write the gui-code for making the functionality available to the user (and state save/recall code).

should i suspend this and first look into the phase-drift? i could try to change the code in the way i suggested above - literally enforcing equidistant zero-crossings instead of my current implicit ways (which may (or may not, i'm not sure) introduce pitch bias due to interpolation)

**Comment by elanhickler** [comment]
could you meet me online now? i want to show you exactly how to phaselock these samples. take a break from the mod stuff. This should be easy to phaselock/tune. I can do it by hand easily, it's pretty ridiculous that the tuner can't do it, you have some fundamentally improper function going on.

**Comment by RobinSchmidt** [comment]
i'm at gmail. are you online there?

**Comment by RobinSchmidt** [comment]
ok - so the next task is to refine the cycle-marks by autocorrelation/pattern-matching. find the best match in some neighbourhood of the fundamental's zero crossings and use the position of that best-match as refined cycle-mark

**Comment by RobinSchmidt** [comment]
i have added a parameter "cycleMarkAlgo" to rsInstantaneousFundamentalEstimator::measureInstantaneousFundamental. you can download the updated repo here:

https://gitlab.com/RobinSchmidt/RSLibAndTests. i don't really know anymore, where the autotuner code is. was this just the convenience function `removePitchModulation` in the experiments and i didn't iclude it into the library? ...and i think, you have also made your own version of this convenience function. if so, you need to change the code where it calls the function mentioned above to try it with the new parameter. i'd recommend to make this algorithm index parameter in your user interface. we may come up with yet different algos and some might be better suited to some signals than others and vice versa.

however, this is an early iteration of the new algo and i couldn't test it very much yet. it also needs some optimization...and the highpass later...

**Comment by elanhickler** [comment]
rsInstantaneousFundamentalEstimator::measureInstantaneousFundamental

![image](https://user-images.githubusercontent.com/9116575/29477625-fd082f86-841d-11e7-97e9-b191f61cb5f4.png)

RSLib\Code\Audio\Sampling\Resampler.cpp

**Comment by elanhickler** [comment]
ok testing

**Comment by elanhickler** [comment]
https://puu.sh/xdzpq/9c7676da62.png

I'm getting similar results as last time. did you test with the samples I gave you? https://github.com/RobinSchmidt/RS-MET/files/1229817/Sylophone_samples_to_phaselock.zip

**Comment by elanhickler** [comment]
i set min max frequency to 20 / 16000 as well, didn't help.

**Comment by elanhickler** [comment]
Sustain`n=A1`rr=4 > pitch drift
Sustain`n=A1`rr=2 > pitch drift
Sustain`n=A2`rr=3 > sporadic pitch wobbles

**Comment by RobinSchmidt** [comment]
phew - this is really hard. i have been experimenting a lot with the 

> Sustainn=A2rr=3 > sporadic pitch wobbles

to see what can be done about the wobbles. a highpass before the autocorrelation didn't seem to help at all. what did reduce the wobbles was to use more aggressive bandpassing to isolate the fundamental (you can then use the zero-crossing based cycle marks again). i don't really know if this leads to a satisfactory solution (it may cause other problems). you can try it in the code by uncommenting the line 882 in Resample.cpp:

```
  //k = 0.1; np = 5; 
  // test - stronger filtering (narrower and steeper - narrowing has more effect)
```

so far, i was using a fixed bandpass with hardcoded parameters. if you find this helpful, i can expose the bandpass parameters as user parameters. i guess, i should then turn it into a proper class with data-members

i suppose, the pitch-drift should be addressed by the other ways i suggested above.

**Comment by RobinSchmidt** [comment]
what exactly are you actually now doing manually to these samples? time-warping them in a way to align the cycles of the various samples of one note?

i'm thinking about maybe making an algorithm that takes in a whole bunch of samples and phase-aligns them - i.e. first compute the cycles marks for all samples and then somehow time-align them

**Comment by elanhickler** [comment]
We have demonstrated that taking the zero crossings, then that to then refine by doing an autocorrelation should work. Any other ideas I think are futile. You should not work on an algorithm that takes a bunch of samples and phase-aligns them. You still have the original problem: You don't know where the cycle marks should be. If you knew that, you could align each sample individual simply based on the desired frequency.

Why are you talking about pitch drift and wobble as if it's a separate problem to be solved with another technique? All these problems are based on the fact that your tuner is just not working.

I could tune/phaselock these samples by hand, so your algorithm should have no problem with it.

**Comment by elanhickler** [comment]
You need to study exactly what your tuner is doing and see where it is going wrong. If you depend on the zero crossing to do an autocorrelation, then what if the zero crossing is not a good place for autocorreation? What if it's a flat part of the signal in the case of a square wave when you should be using the edge? I don't know what you're doing of course.

**Comment by elanhickler** [comment]
Wait, how does autocorrelation even help us figure out what "equidistance" is of the waveform?

**Comment by elanhickler** [comment]
I think I need to go through the process of phaselocking something by hand and figure out what a solution might be.

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/29484106-a23d7d82-846c-11e7-9bca-257ae69a622a.png)
![image](https://user-images.githubusercontent.com/9116575/29484112-c6b9dae8-846c-11e7-9796-dc292b515491.png)
![image](https://user-images.githubusercontent.com/9116575/29484121-ed886cac-846c-11e7-8423-35a116d2755a.png)
![image](https://user-images.githubusercontent.com/9116575/29484142-5613549e-846d-11e7-8b77-f1a9dd99b5e3.png)
![image](https://user-images.githubusercontent.com/9116575/29484181-0bc4c584-846e-11e7-8635-5c3e6d2731a7.png)

**Comment by elanhickler** [comment]
here's another view of the old and new position
![image](https://user-images.githubusercontent.com/9116575/29484222-ef248b0c-846e-11e7-8d5f-e553e00e9f72.png)

**Comment by elanhickler** [comment]
here's another view of the original tuning errors, where gaps mean that the cycle was not long enough (low enough in frequency to be exactly at A2 frequency)
![image](https://user-images.githubusercontent.com/9116575/29484246-5a975518-846f-11e7-8b5a-b352e747f0f6.png)

**Comment by elanhickler** [comment]
using our cycle snippets we can mark out exactly where in the waveform your "cycle marts/tuning marks" need to be placed
![image](https://user-images.githubusercontent.com/9116575/29484280-0797e340-8470-11e7-9dc1-f05d97c3c00d.png)

see animation: https://puu.sh/xdUFC/ae433d65b5.gif

**Comment by RobinSchmidt** [comment]
> Why are you talking about pitch drift and wobble as if it's a separate problem

because, i think it is. pitch drift means that, for some reason, the average pitch doesn't come out right which points to some bias (i.e. error in the average) in the analysis data. cycle-mark misplacements must average out and can't give rise to such a thing. so it must be related to some of the postprocessing steps, i.e. what i subsequently do with the cycle-marks

> I could tune/phaselock these samples by hand, so your algorithm should have no problem with it.

uuuhh....well...taken as a general proposition, i wouldn't subscribe to that. what is virtually effortless to humans can be rather hard to teach machines indeed (and vice versa). just take face recognition as example.

in this case, however, i can see a possible algorithmic solution. if what you are doing by hand is to manually cut the cycles to some sepcified length, that's actually somewhat akin to granular synthesis. no wonder that we are getting nowhere with an algorithm based on an entirely different approach to equalize the cycle length (namely: time-warping). 

also, it seems that, if the cycles are indeed of different length, the detected wobble in the pitch is a legitimate signal feature and not "jitter-error" in the pitch detector. 

soo, i would propose that instead of time-warping, we try something granular. it doesn't seem to be the fault of the cycle-mark detector but rather what we do with those marks afterwards

**Comment by elanhickler** [comment]
It *must* be rate tuned / time-warped. Absolutely do not use a grainulular approach to manipulating the audio.

**Comment by elanhickler** [comment]
Come on Robin, I'm showing you exactly what your algorithm needs to do, yet you somehow read it as "granular" approach.

**Comment by elanhickler** [comment]
Just because I am showing you "grains" does not mean I am telling you take a granular approach. I'm showing you how your algorithm can find where the exact cycle marks should be placed per cycle.

**Comment by elanhickler** [comment]
> what is virtually effortless to humans can be rather hard to teach machines indeed (and vice versa)

In this case, autocorrelation is a lot of effort for me the human, effortless for a machine!

**Comment by elanhickler** [comment]
Tuning via grains will not only NOT solve the problem, it will suffer from distortion. I was using a granular some years ago before I hired you. The problem is that your algorithm doesn't know where a cycle starts and ends. That will be a problem still with a granular approach.

**Comment by elanhickler** [comment]
I've been phaselocking signals with a time warp / rate tuning approach for a while now, when your tuner would work.

**Comment by elanhickler** [comment]
so the tuner is not working today, now I'll really have to do the entire project by hand. We are out of time. But keep working on this, let me know if you're going over $200. This tuner is critical for my business.

**Comment by elanhickler** [comment]
I'll do it by hand by marking the cycles via manual-human-auto-correlation by taking every n cycles (more cycles at the attack since the attack is particularly out of tune), using those cycles to do "cycle marks" then use REAPER's stretch markers to smoothly timewarp it into equidistant cycles.

**Comment by elanhickler** [comment]
sorry for sounding frustrated, i'd be really in trouble if i lost you

**Comment by elanhickler** [comment]
We will have waveform view, playback, and rate tuning for SeSalt in the future, maybe then we can also create a great platform for you to test these kinds of things in the future by calling your functiosn via SeSalt javascript and seeing the results in various ways (being able to place markers, envelope points, whatever you want to see)

**Comment by elanhickler** [comment]
Step 1: Extract the fundmanetal harmonic via bandpass filter
Step 2: Split the original signal into segments based on the zero crossings of the fundamental. They will be different lengths.
Step 3: Autocorrelate each segment with its neighbor to get the start time of each segment required for best autocorrelation position. Now, what is the lastest start time? See where that start time hits every segment. That's where your cycle marks go.
Step 4: Time warp. Done.

**Comment by elanhickler** [comment]
I made a video
https://youtu.be/RgJH6Np4by0

**Comment by elanhickler** [comment]
I just finished the project that I needed to tuner for, using my general tuner Helmholtz and fine-tuning by using a phase alignment technique, making use of 100% time warping / rate warping.

**Comment by elanhickler** [comment]
well f*** it failed because of tiny inaccuracies causing drift by the non-phaselocking tuner. It's phaselocked until you try to loop it.

**Comment by elanhickler** [comment]
I had to do another round of tuning/phase corrections for looping... but it's not perfect due to tiny drifts from the non-phaselocking tuner.

**Comment by RobinSchmidt** [comment]
when i was thinking about granular, i was taking this:

> cut away the excess/error so you are left with cycles that are exactly the same lenght (will be shorter than the period/cycle length)

literally. when you really do this, then you are in effect taking grains where the grain-length is the cycle-length that you cut it to.  ..but so you mean you don't really do this cutting but somehow used it as demonstration for how the cycle-lengths should end up after warping?

i have refactored the code now, so we can more easily access (and inspect) the results of the cycle-mark finding process. there's a new class rsCycleMarkFinder. maybe you can turn that into a reaper plugin and use it to find the cycle marks so we can exactly see, where and when misplacements occurr, if any? you have also access to some of the internal parameters that were previously hardcoded. just look at the comments of the setter functions

>  Step 3: Autocorrelate each segment with its neighbor to get the start time of each segment required for best autocorrelation position. Now, what is the segment with the latest start time? See where that start time hits every segment. That's where your cycle markers go.

i don't really understand what you mean by "the start time of the last segment hits every segment". can you elaborate this? i always put the cycle next marker at the position where i get maximum correlation with previous cycle

**Comment by elanhickler** [comment]
My demonstration is just to visualize something. Putting cycle markers at maximum correlation is probably the same thing. Maybe. Let's see what your cycle markers are doing before we continue this endeavor.

**Comment by elanhickler** [comment]
ok did some tests, when using algorithm 0 there's jitter but it's almost perfectly phaselocked, weird... zero crossing shouldn't be doing this well...

When using algorithm 1 it looks like the results WOULD BE better EXCEPT there's a constant speed drift, wtf?

**Comment by RobinSchmidt** [comment]
can you tell me exactly which sample it is that exposes the drift? or alternatively, you could try to change line 298, where its says:

`double delta = rsMaxPosition(&corr[0], 2*length-1) - length + 1.5; // is +1.5 correct? was found by trial and error`

this  `+ 1.5` could well be responsible for the drift, if it is indeed wrong. maybe try values of 1.0, 0.5 or even 0.0. i wasn't sure what the correct value has to be

**Comment by RobinSchmidt** [comment]
or...wait...i see another potential bug, line 257: `return i - offset;` could have to be `return i + offset;`. maybe best tell me what sample to experiment with to iron this out myself

**Comment by RobinSchmidt** [comment]
....it's probably (hopefully) just a simple bug

**Comment by RobinSchmidt** [comment]
> Also, between two samples (of the same note, A1), the drift speed was different, wtf * 2.

but it's always in the same direction? i.e. the marks always drift apart (or together?)

**Comment by elanhickler** [comment]
Looks like some instances have back and forth drift as if the frequency counter is only updated every so often, except cycle markers is not based on frequency. All A1 samples have various issues.

**Comment by RobinSchmidt** [comment]
maybe it would be best, if i could play around with the algorithms in reaper myself. it's a bit cumbersome to set up test-functions and work with gnuplot for every test that i make. it has advantages, too like having very precise control over inputs, reproducibility, etc. but i think, i need to test the code in a more realistic real-world setting. so, how does this work with the reaper actions?

**Comment by RobinSchmidt** [comment]
however, i think, i will first make sure that the subsample-maximum-position finder is indeed correct (i.e. the + or - offset). i can do that in a unit test

btw.: what i'm doing there is to find the index of the maximum, look at the left and right neighbours and fit a parabola to these 3 values and take the maximum of the parabola as subsample-maximum position

**Comment by elanhickler** [comment]
ok tell me what you want and I'll make it happen.

**Comment by RobinSchmidt** [comment]
can we have a repository with your reaper actions that make use of my library functions? then, i could build and use them in reaper on my pc and modify my library code and directly see the modifications "in action" in a real-life situation

**Comment by RobinSchmidt** [comment]
because my tests are often very much constructed examples. although i often try to construct them in ways that are supposed to expose errors, an actual real-life sample might be different

**Comment by elanhickler** [comment]
ok im going to work on cleaning up some code for this. should be done in a day or two. In the mean time, I'm still desperate to get Spiral Generator 3.0 created with a modulation system!

**Comment by elanhickler** [comment]
err... desperate to get a synthesizer product out for sale. I need to do Spiral Generator, Torus Generator, Boing, Radar, I need to do a lot. It will be a $50 product I think, that comes with all of those.

**Comment by RobinSchmidt** [comment]
ok, it's mostly only the gui and state-recall stuff left. and testing the system in practice. maybe a few days.

**Comment by elanhickler** [comment]
I have a working example in REAPER of CycleMarkFinder

![image](https://user-images.githubusercontent.com/9116575/31203693-15f0617a-a91d-11e7-92bb-9f7cad87800f.png)

It is suffering from a small constant drift, as stated before. Other than that, the results looks promising.

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/31204235-c84de9bc-a91f-11e7-8cd9-162c133ad88f.png)

1. get repoistory: https://github.com/gregjazz/reaper_OTSplugin
2. create VS project using JUCER of course.
3. build, don't forget to make the rslib config work
4. put the resulting dll plugin into REAPER/UserPlugins

**Comment by elanhickler** [comment]
Robin, get on this as soon as possible and send me a bill. Just make sure you keep tasks separate in the bill. There's a lot of work to do this month!

**Comment by RobinSchmidt** [comment]
> build, don't forget to make the rslib config work

what do you mean by that? the custom edits that you had to apply to make it compile? if so, what exactly were these? do you have a textfile with instructions for these?

also, in what (relative) folder is the RSLib library code supposed to reside? and what it this "seObjectiveReaper" juce module that seems to be required but not included?

**Comment by elanhickler** [comment]
oops forgot: https://github.com/elanhickler/seObjectiveReaper

everything goes next to the OTS repository, e.g:

![image](https://user-images.githubusercontent.com/9116575/31287798-5bdf8066-aa77-11e7-9ae3-72bf313244e2.png)

**Comment by elanhickler** [comment]
to get rslib the compile, follow your own instructions 👍

**Comment by RobinSchmidt** [comment]
yeah - but where are they? i thought, you have made a textfile for them? could you just include that? i mean, it makes sense for you to have it there anyway, doesn't it?

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/31287951-f29bb88a-aa77-11e7-9a5a-e58c8a5b4eb0.png)

Before, your RSCore.h file read #Include <RSBuildConfig.h>, didn't know how to make that the location of the config file, so I just changed it:

![image](https://user-images.githubusercontent.com/9116575/31287985-0cafef16-aa78-11e7-84a2-e270470e8d30.png)

**Comment by elanhickler** [comment]
btw you can make changes to make all this more correct/easier, I don't know how.

**Comment by RobinSchmidt** [comment]
ahh - that's what you are talking about. i was talking about some code changes that had to be applied to library code due to the compiler complaining (for reasons, we didn't figure out at that time). ok, i'll try..

**Comment by elanhickler** [comment]
to scan through the markers to get an idea of how the markers drift, hold down a hotkey:

![image](https://user-images.githubusercontent.com/9116575/31289716-9d20743e-aa7e-11e7-97ee-1824da75d0e0.png)

If you don't find any drift in the sample you are using, let me know.

**Comment by elanhickler** [comment]
edit: f*** that's a custom action.

**Comment by RobinSchmidt** [comment]
i had to add some include paths to the jucer project and change some include in a cpp file - now i can compile, but get a linker error:

LNK2005	"void __cdecl GUI::testUserInputs(void)" (?testUserInputs@GUI@@YAXXZ) already defined in gui_text_editor.obj	reaper_OTSplugin	E:\Programming\C++\ElansReaperPlugins\reaper_OTSplugin\Builds\VisualStudio2015\main.obj

do you have an idea what this could be?

**Comment by elanhickler** [comment]
oh, i think i forgot to update the jucer

**Comment by elanhickler** [comment]
try now, pull update

**Comment by RobinSchmidt** [comment]
your update didn't change anything. same error. however, i could fix it by placing an "inline" before testUserInputs in gui_text_editor.h. i can now build it (compile + link). but why do i have to patch your code to make it build? ..or wait - is this even your code or is this part of the plugin-sdk?

well, ok, let's see now, how it works in reaper..

**Comment by elanhickler** [comment]
what do you mean it didn't change anything? you should not have any files that say gui_etc.

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/31310940-9a757f80-ab56-11e7-9b3b-ab686455a22a.png)

**Comment by elanhickler** [comment]
this was solved
